# Sử dụng python 3.10-slim-bookworm (Bản ổn định cho Debian 12)
FROM python:3.10-slim-bookworm

# Thiết lập biến môi trường
ENV TF_USE_LEGACY_KERAS=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

WORKDIR /app

# Cài đặt thư viện hệ thống (libgl1 cho OpenCV)
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY src/requirements.txt .

# Cài đặt thư viện Python
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy source code (CHỈ COPY SRC, KHÔNG COPY MODELS)
COPY src/ ./src/

# EXPOSE PORT
EXPOSE 8000

# Chạy ứng dụng
CMD ["python", "src/scripts/main.py"]